apiVersion: v1
kind: Pod
metadata:
  name: simple-hello-world
  labels:
    app: simple-hello-world
spec:
  containers:
  - name: simple-hello-world
    image: ondrejsika/go-hello-world:2
    ports:
    - containerPort: 80
