apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world-deploy
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world-deploy
    spec:
      containers:
      - name: hello-world
        image: ondrejsika/go-hello-world:2
        ports:
        - containerPort: 80