apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-redis
spec:
  selector:
    matchLabels:
      project: counter
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        project: counter
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: counter-redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    project: counter
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-counter
spec:
  selector:
    matchLabels:
      project: counter
      app: counter
  replicas: 2
  template:
    metadata:
      labels:
        project: counter
        app: counter
    spec:
      containers:
      - name: counter
        image: ondrejsika/counter
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
        env:
        - name: REDIS
          value: counter-redis
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: counter-counter
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    project: counter
    app: counter