---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-example
spec:
  selector:
    matchLabels:
      app: secret-example
  replicas: 1
  template:
    metadata:
      labels:
        app: secret-example
    spec:
      containers:
      - name: www
        image: ondrejsika/www
        volumeMounts:
        - name: secret
          mountPath: /www/secret.txt
          subPath: key.txt
        - name: config
          mountPath: /www/config.txt
          subPath: config
      volumes:
      - name: config
        configMap:
            name: my-config
      - name: secret
        secret:
          secretName: my-secret
          items:
          - key: key
            path: key.txt
---
apiVersion: v1
kind: Service
metadata:
  name: secret-example
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: secret-example