---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-example
spec:
  selector:
    matchLabels:
      app: secret-example
  replicas: 1
  template:
    metadata:
      labels:
        app: secret-example
    spec:
      containers:
      - name: www
        image: ondrejsika/www
        env:
        - name: MY_KEY
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: key
        - name: MY_TOKEN
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: token
        volumeMounts:
        - name: secret
          mountPath: /www/secret.txt
          subPath: key
        - name: config
          mountPath: /www/config.txt
          subPath: config
        - name: config
          mountPath: /www/hello.html
          subPath: index.html
        resources:
          requests:
            memory: 10Mi
            cpu: 10m
          limits:
            memory: 20Mi
            cpu: 20m
      volumes:
      - name: config
        configMap:
            name: my-config
      - name: secret
        secret:
          secretName: my-secret
---
apiVersion: v1
kind: Service
metadata:
  name: secret-example
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: secret-example
