apiVersion: v1
kind: Pod
metadata:
  name: private-pod
spec:
  containers:
  - name: hello
    image: registry.sikahq.com/pseudo-private/hello-world:latest
  imagePullSecrets:
  - name: private-registry-credentials
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: private-registry-credentials
data:
  .dockerconfigjson: eyJhdXRocyI6IHsicmVnaXN0cnkuc2lrYWhxLmNvbSI6IHsiYXV0aCI6ICJjSE5sZFdSdkxYQnlhWFpoZEdVdGRYTmxjanBoYzJSbVlYTmtaZz09In19fQ==