apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness
spec:
  replicas: 5
  selector:
    matchLabels:
      app: liveness
  template:
    metadata:
      labels:
        app: liveness
    spec:
      containers:
      - image: ondrejsika/health
        name: health
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
        resources:
          requests:
            memory: 10Mi
            cpu: 10m
          limits:
            memory: 20Mi
            cpu: 20m
