apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness
spec:
  replicas: 5
  selector:
    matchLabels:
      app: readiness
  template:
    metadata:
      labels:
        app: readiness
    spec:
      containers:
      - image: ondrejsika/health
        name: health
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 5
        resources:
          requests:
            memory: 10Mi
            cpu: 10m
          limits:
            memory: 20Mi
            cpu: 20m
