apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: readiness
spec:
  replicas: 5
  selector:
    matchLabels:
      app: readiness
  template:
    metadata:
      labels:
        app: readiness
    spec:
      containers:
      - image: ondrejsika/health
        name: health
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 5